version: "3"

services:
  mongo:
    image: mongo
    container_name: mongodb
    command: --serviceExecutor adaptive
    restart: always
  aplicacao:
    build: .
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
    restart: always
    depends_on: 
      - mongo
    