version: "3"

services:
  mongo:
    container_name: mongodb
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    ports: 
      - "27017:27017"
  api:
    container_name: clean-node-api-container
    build: .
    image: clean-node-api
    restart: always
    command: npm start
    volumes:
      - ./dist:/usr/src/clean-node-api/dist
    ports:
      - "3000:3000"
    links:
      - mongo
    