version: "3"

services:
  mongo:
    container_name: mongodb
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    ports: 
      - "27017:27017"
  api:
    container_name: clean-node-api-container
    image: node:14
    restart: always
    working_dir: /usr/src/clean-node-api
    command: bash -c "npm install && npm run debug"
    environment:
      - MONGO_URL=mongodb://mongo:27017/clean-node-api
    volumes:
      - ./:/usr/src/clean-node-api/
      - ./package.json:/usr/src/clean-node-api/package.json
    ports:
      - "3000:3000"
      - "9222:9222"
    links:
      - mongo
    depends_on: 
      - mongo
    